language: python
python:
 - "2.7"
env:
 global:
   - "ARTIFACTS_AWS_REGION=us-east-1"
   - "ARTIFACTS_S3_BUCKET=alistra-cv"
   - secure: "h7IwcPmKP+/s3CF+ydxVGK/2fJQO3/v1Yfncto1FWvCm00Vc22P23s9SoYsN\niWNty1GM0THAHgVR4RxU35p2S5LN3qHfWvWPvv4Je+GoA7WO2v6MubGaZl8J\n2e4j/RyzshvSpD9EWbcj/YCzbdAxZo0XvbDs6dWkbPr6Jte5MkU="
   - secure: "GWhd1ALFg9Rt1wYDyIeBrl+qcEcgmTDM40rii4CnYJi0lgZKF/Iys+lTsRVI\ngORD8goxwBmStLoNptVdLgLfDDCybLDNVmcK6yztQ3mzo5+JEs6ke9ePU5cG\n8eJ7HQf78oBcUPpdCASFgYWHkVu9SYIClsOBD0+NASp9v2qnohQ="

before_install:
 - sudo apt-get update --fix-missing
 - sudo apt-get install rubber
 - sudo apt-get install texlive-latex-extra
 - sudo apt-get install texlive-latex-recommended
 - sudo apt-get install texlive-math-extra
before_script:
 - gem install travis-artifacts
after_success:
 - travis-artifacts upload --path cv.pdf
 - travis-artifacts upload --path cv.pdf --target-path "current"
script: "make"
